# build
FROM golang:1.26-alpine AS backend-builder
WORKDIR /app
RUN go env -w GOCACHE=/go-cache
RUN go env -w GOMODCACHE=/go-mod-cache
COPY backend/app/go.mod backend/app/go.sum ./
RUN --mount=type=cache,target=/go-mod-cache go mod download
COPY backend/app/ ./
COPY backend/migrations ./migrations
RUN mkdir -p frontend/build && echo 1 > frontend/build/file.txt
RUN --mount=type=cache,target=/go-cache \
    --mount=type=cache,target=/go-mod-cache \
    go build \
    -tags='no_postgres no_clickhouse no_mssql no_mysql' \
    -o macro .

# run
FROM alpine:latest
WORKDIR /app
COPY --from=backend-builder /app/macro .
EXPOSE 8080
CMD ["./macro"]