# fronend
FROM node:20-alpine AS frontend-builder
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build

# backend
FROM golang:1.26-alpine AS backend-builder
WORKDIR /app
RUN go env -w GOCACHE=/go-cache
RUN go env -w GOMODCACHE=/go-mod-cache
COPY backend/app/go.mod backend/app/go.sum ./
RUN --mount=type=cache,target=/go-mod-cache go mod download
COPY backend/app/ ./
COPY backend/migrations ./migrations
COPY --from=frontend-builder /app/build ./frontend/build
RUN --mount=type=cache,target=/go-cache \
    --mount=type=cache,target=/go-mod-cache \
    CGO_ENABLED=0 \
    GOOS=linux \
    go build \
    -ldflags="-s -w" \
    -tags='no_postgres no_clickhouse no_mssql no_mysql' \
    -o macro .

# fullstack (production)
FROM gcr.io/distroless/static-debian12:latest AS distroless
COPY --from=backend-builder /macro .
EXPOSE 8080
CMD ["/macro"]

# alpine (debug)
FROM alpine:latest AS alpine
COPY --from=backend-builder /macro .
EXPOSE 8080
CMD ["/macro"]

# goose (migration tool)
FROM golang:1.26-alpine AS goose-builder
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

FROM alpine:latest AS goose
COPY --from=goose-builder /go/bin/goose /usr/local/bin/goose
WORKDIR /app