services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend/macro.db:/app/macro.db
    ports:
      - "8080:8080"
  
  golang:
    image: golang:1.26-alpine
    volumes:
      - ./backend/app:/app
    working_dir: /app
  
  goose:
    build:
      context: .
      dockerfile: Dockerfile.goose
    volumes:
      - ./backend/macro.db:/app/macro.db
      - ./backend/migrations:/app/migrations
    environment:
      - GOOSE_DRIVER=sqlite3
      - GOOSE_DBSTRING=/app/macro.db
      - GOOSE_MIGRATION_DIR=/app/migrations
    working_dir: /app
    command: sh

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.js:/app/vite.config.js
      - ./frontend/package.json:/app/package.json
    ports:
      - "5173:5173"
  
  npm:
    image: node:20-alpine
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.js:/app/vite.config.js
      - ./frontend/package.json:/app/package.json
    working_dir: /app
    command: sh