secrets:
  session_secret:
    file: ./session_secret.txt

services:
  fullstack:
    build:
      context: .
      target: distroless
    volumes:
      - ./backend/data:/app/data
    secrets:
      - session_secret
    ports:
      - "8080:8080"

  backend:
    build:
      context: .
      target: backend-builder
    volumes:
      - ./backend/data:/app/data
      - ./backend/app:/app/src
    environment:
      - DEVMODE=true
    secrets:
      - session_secret
    ports:
      - "8080:8080"
    command: air

  frontend:
    build:
      context: .
      target: frontend-builder
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.js:/app/vite.config.js
      - ./frontend/package.json:/app/package.json
    environment:
      - DEVMODE=true
    ports:
      - "5173:5173"
    command: npm run dev -- --host
  
  goose:
    build:
      context: .
      target: goose
    volumes:
      - ./backend:/app
    environment:
      - GOOSE_DRIVER=sqlite3
      - GOOSE_DBSTRING=/app/data/macro.db
      - GOOSE_MIGRATION_DIR=/app/migrations
    working_dir: /app