package main

import (
	"crypto/rand"
	"encoding/hex"
)

// GenerateRandomBytes generates a slice of random bytes of the specified length. It uses the
// crypto/rand package to ensure that the generated bytes are cryptographically secure, making it
// suitable for use in scenarios like generating session secrets or other sensitive data.
func GenerateRandomBytes(n int) []byte {
	defer Trace("GenerateRandomBytes(n)", "n", n)()

	b := make([]byte, n)
	rand.Read(b) // Documented to never return an error on all but legacy Linux systems

	return b
}

// GenerateRandomHexString generates a random hexadecimal string of the specified length (in bytes).
// It first generates a slice of random bytes using the GenerateRandomBytes function, and then
// encodes those bytes into a hexadecimal string using the encoding/hex package. The resulting
// string will be twice as long as the input byte length, since each byte is represented by two
// hexadecimal characters.
func GenerateRandomHexString(n int) string {
	defer Trace("GenerateRandomHexString(n)", "n", n)()

	b := GenerateRandomBytes(n)
	return hex.EncodeToString(b)
}
