# build
FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build  \
    -tags='no_postgres no_clickhouse no_mssql no_mysql' \
    -o macro .


# run
FROM alpine:latest
WORKDIR /root
COPY --from=builder /app/macro .
EXPOSE 8080
CMD ["./macro"]